version: '3'
services:

#Nginx Server
  webserver:
    image: nginx
    container_name: "${PREFIX}nginx"
    restart: unless-stopped
    volumes:
      - ./public:/var/www/public
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    depends_on:
      - php

#PHP
  php:
    build:
      context: images/php
    container_name: "${PREFIX}php"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./public:/var/www/public
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./config/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

#PostgreSQL
  pgsql:
    image: postgres:15.1
    container_name: "${PREFIX}postgresql"
    restart: unless-stopped
    ports:
      - "${PGSQL_PORT}:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${PGSQL_USER}"
      POSTGRES_PASSWORD: "${PGSQL_PASSWORD}"
      POSTGRES_DB: "${PGSQL_DB}"

#MySQL
  mysql:
    image: mysql:5.7
    container_name: "${PREFIX}mysql"
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
