version: '3'
services:

#Nginx
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./_docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php

#PHP
  php:
    build:
      context: _docker/php
      args:
        - UID=${LOCAL_UID:-1000}
        - GID=${LOCAL_GID:-1000}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/var/www
      - ./_docker/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./_docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

#PostgreSQL
  pgsql:
    build:
      context: _docker/postgresql
      args:
        - UID=${LOCAL_UID:-1000}
        - GID=${LOCAL_GID:-1000}
    restart: unless-stopped
    ports:
      - "${PGSQL_PORT}:5432"
    volumes:
      - pgsql-database:/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${PGSQL_USER}"
      POSTGRES_PASSWORD: "${PGSQL_PASSWORD}"
      POSTGRES_DB: "${PGSQL_DB}"

#MySQL
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-database:/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"

volumes:
  mysql-database:
    driver: local
  pgsql-database:
    driver: local