version: '3'
services:
  webserver:
    image: nginx
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    build:
      context: php
    environment:
      - PHP_IDE_CONFIG=serverName=magic
    volumes:
      - ./public:/var/www/public
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./config/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini